export const Untracked = '??'
export const Ignored = '!!'
export const BothDeleted = 'DD'
export const AddedByUs = 'AU'
export const DeletedByThem = 'UD'
export const AddedByThem = 'UA'
export const DeletedByUs = 'DU'
export const BothAdded = 'AA'
export const BothModified = 'UU'

export const IndexModified = 'M'
export const IndexAdded = 'A'
export const IndexDeleted = 'D'
export const IndexRenamed = 'R'
export const IndexCopied = 'C'
export const TypeChanged = 'T'

export const Modified = 'M'
export const Deleted = 'D'
export const Added = 'A'
