export const RepositoriesGetCurrent = 'Repositories.getCurrent'
export const ExecExec = 'Exec.exec'
export const QuickPickShow = 'QuickPick.show'
export const ConfigGetWorkspaceFolder = 'Config.getWorkspaceFolder'
export const ConfigGetGitPaths = 'Config.getGitPaths'
